### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by winzou** [joshbmarshall/payum_airwallex#1]
Hi @joshbmarshall Thanks for this package! How ready for production is this? What are the Airwallex methods you are already using? I'm looking into using this as well on my side. Thanks!

**Comment by joshbmarshall** [comment]
Yes I'm using it in production already. Basically just taking funds only. It does use auth then capture so if comms stops after credit card information is sent to airwallex it doesn't complete the capture.

For details you could look at my code, there isn't much functionality but working enough for my use, which is mainly taking funds for payment inbound.

⁣Get BlueMail for Android ​

**Comment by joshbmarshall** [comment]
Also can specify the currency to take the funds in, that's really useful.

⁣Get BlueMail for Android ​
