### ISSUE TITLE
 composer require cognito/payum_airwallex 

### ISSUE THREAD

**Issue by qwXaleyLid** [joshbmarshall/payum_airwallex#2]
Composer version 1.10.27

  Problem 1
    - cognito/payum_airwallex 1.1.0 requires payum/core ^1.5 -> satisfiable by payum/core[1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.7.2, 1.7.3, 1.7.4].
    - cognito/payum_airwallex 1.1.1 requires payum/core ^1.5 -> satisfiable by payum/core[1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.7.2, 1.7.3, 1.7.4].
    - payum/core 1.7.4 requires php-http/client-implementation ^1.0 -> no matching package found.
    - payum/core 1.7.3 requires php-http/client-implementation ^1.0 -> no matching package found.
    - payum/core 1.7.2 requires php-http/client-implementation ^1.0 -> no matching package found.
    - payum/core 1.7.0 requires php-http/client-implementation ^1.0 -> no matching package found.
    - payum/core 1.6.3 requires php-http/client-implementation ^1.0 -> no matching package found.
    - payum/core 1.6.2 requires php-http/client-implementation ^1.0 -> no matching package found.
    - payum/core 1.6.1 requires php-http/client-implementation ^1.0 -> no matching package found.
    - payum/core 1.6.0 requires php-http/client-implementation ^1.0 -> no matching package found.
    - Installation request for cognito/payum_airwallex ^1.1 -> satisfiable by cognito/payum_airwallex[1.1.0, 1.1.1].

**Comment by joshbmarshall** [comment]
Have you got payum installed and working? https://payum.gitbook.io/payum/get-it-started
